import { Wallet } from "fuels";

// Import the contract factory from the folder generated by the fuelchain

import LoginForm from "./LoginForm";
import WalletView from "./WalletView";

// The private key of the `owner` in chainConfig.json.
// This enables us to have an account with an initial balance.
const WALLET_ONE_SECRET =
  "0xa449b1ffee0e2205fa924c6740cc48b3b473aa28587df6dab12abc245d1f5298";
const WALLET_TWO_SECRET =
  "0x6a1f7d4a163367b4792ec45a0e9df6b955a91847160a899c0c8a2d61722a2441";
const WALLET_THREE_SECRET =
  "0x1a869d2ca27dc5686f81665e500109c979ad21e78dc6f6dfc39f3ce35d4c0db5";
const WALLET_FOUR_SECRET =
  "0x8139b813b20924190484a049005fb5c19e2f85e1c7e02d26f25a5f6a1cceccb1";

// The ID of the contract deployed to our local node.
// The contract ID is displayed when the `forc deploy` command is run.
// E.g. Contract id: 0xa326e3472fd4abc417ba43e369f59ea44f8325d42ba6cf71ec4b58123fd8668a
// const CONTRACT_ID = "0xa326e3472fd4abc417ba43e369f59ea44f8325d42ba6cf71ec4b58123fd8668a"
const CONTRACT_ID =
  "0xd97ac31a1a473e6dd6f7dfdaf773a2a4df452ec3445afd291298b48dcea57cd3";

// Create a "Wallet" using the private key above.
const wallet = new Wallet(WALLET_ONE_SECRET);

// Connect a "Contract" instance using the ID of the deployed contract and the
// wallet above.
// const contract = ContractsAbi__factory.connect(CONTRACT_ID, wallet);

function App() {
  return (
    <>
      <div className="h-screen bg-green-100 w-100">
        <div className="flex flex-col justify-center min-h-full py-12 sm:px-6 lg:px-8">
          <div className="sm:mx-auto sm:w-full sm:max-w-md">
            {/* <img
                            className="w-auto h-12 mx-auto"
                            src="https://tailwindui.com/img/logos/mark.svg?color=emerald&shade=600"
                            alt="Your Company"
                        /> */}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              className="w-12 h-12 mx-auto text-emerald-400"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z"
              />
            </svg>

            <h2 className="mt-2 text-4xl font-bold tracking-tight text-center text-gray-900 text-emerald-700">
              Authsome
            </h2>
            <p className="text-lg text-center text-emerald-700">
              Create your multi-sig wallet.
            </p>
          </div>
          <LoginForm />
        </div>
      </div>
      <div className="h-screen bg-green-100 w-100">
        <div className="flex flex-col justify-center min-h-full py-12 sm:px-6 lg:px-8">
          <div className="sm:mx-auto sm:w-full sm:max-w-md">
            {/* <img
                            className="w-auto h-12 mx-auto"
                            src="https://tailwindui.com/img/logos/mark.svg?color=emerald&shade=600"
                            alt="Your Company"
                        /> */}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              className="w-12 h-12 mx-auto text-emerald-400"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z"
              />
            </svg>

            <h2 className="mt-2 text-4xl font-bold tracking-tight text-center text-gray-900 text-emerald-700">
              Wallet
            </h2>
            <p className="text-lg text-center text-emerald-700">
              See and send assets.
            </p>
          </div>
          <WalletView />
        </div>
      </div>
    </>
  );
}

export default App;
